{
  "openapi": "3.1.0",
  "info": {
    "version": "0.0.1-alpha",
    "title": "Spring Boot API",
    "description": "Spring Boot Restful API",
    "contact": {
      "name": "IDScript",
      "email": "spring@idscript.com",
      "url": "https://spring.idscript.com"
    },
    "license": {
      "name": "MIT",
      "url": "https://spring.idscript.com/LICENSE.md"
    }
  },
  "servers": [
    {
      "description": "Spring Boot Restful API",
      "url": "https://spring.idscript.com/{environment}/v1",
      "variables": {
        "environment": {
          "description": "Server Environment",
          "default": "api",
          "enum": [
            "dev",
            "test",
            "api"
          ]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "Find out more about WhatsAPI",
    "url": "https://spring.idscript.com/docs"
  },
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "User Management"
        ],
        "summary": "User Registration",
        "description": "Endpoint for user rehistration",
        "requestBody": {
          "description": "User Data",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/register"
              },
              "examples": {
                "example": {
                  "description": "User Data for registeration",
                  "value": {
                    "name": "example name",
                    "username": "example",
                    "password": "Secret"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "message": {
                      "type": "string",
                      "maxLength": 100,
                      "pattern": "[\\n\\s\\w\\W^$]"
                    },
                    "data": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "token": {
                          "type": "string",
                          "maxLength": 100,
                          "pattern": "[\\n\\s\\w\\W^$]"
                        },
                        "name": {
                          "type": "string",
                          "maxLength": 100,
                          "pattern": "[\\n\\s\\w\\W^$]"
                        },
                        "username": {
                          "type": "string",
                          "maxLength": 100,
                          "pattern": "[\\n\\s\\w\\W^$]"
                        }
                      }
                    },
                    "meta": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "location": {
                          "type": "string",
                          "maxLength": 100,
                          "pattern": "[\\n\\s\\w\\W^$]"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Success Add device",
                    "value": {
                      "message": "User Created",
                      "data": {
                        "token": "jncksdc7bdjb6r7ausvb",
                        "name": "example name",
                        "username": "example"
                      },
                      "meta": {
                        "location": "https://api/v1/user/1"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "User Management"
        ],
        "summary": "User List",
        "description": "Endpoint for show Users List",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Forbidden"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": [
          "User Management"
        ],
        "summary": "User Login",
        "description": "Endpoint for User Login",
        "requestBody": {
          "description": "ID dari device yang ingin ditambahkan.",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/login"
              },
              "examples": {
                "example": {
                  "description": "Login request body",
                  "value": {
                    "username": "example",
                    "password": "Secret"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/{user_id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "User Management"
        ],
        "summary": "Get User Data",
        "description": "Endpoint for Get User Data",
        "parameters": [
          {
            "$ref": "#/components/parameters/user_id"
          }
        ],
        "responses": {
          "200": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Forbidden"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "User Management"
        ],
        "summary": "Update User Data",
        "description": "Endpoint for Update User Data",
        "parameters": [
          {
            "$ref": "#/components/parameters/user_id"
          }
        ],
        "requestBody": {
          "description": "Data dari user yang ingin update.",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/login"
              },
              "examples": {
                "Update Name": {
                  "description": "Update name",
                  "value": {
                    "name": "New Name"
                  }
                },
                "Update password": {
                  "description": "Update password",
                  "value": {
                    "password": "NewPassword"
                  }
                },
                "Update Name and Password": {
                  "description": "Update name",
                  "value": {
                    "name": "New Name",
                    "password": "NewPassword"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Forbidden"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "User Management"
        ],
        "summary": "User LogOut",
        "description": "Endpoint for User Logout",
        "responses": {
          "204": {
            "description": "The resource was deleted successfully"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Contact Management"
        ],
        "summary": "Add User Contact",
        "description": "Endpoint for Add User Contact",
        "requestBody": {
          "description": "User Contact Data",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/contactReq"
              },
              "examples": {
                "Add Contact": {
                  "description": "User Data for Add User Contact",
                  "value": {
                    "firstName": "firstName",
                    "lastName": "lastName",
                    "email": "email@email.com",
                    "phone": "1234567890"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/contactRes"
                },
                "examples": {
                  "success": {
                    "description": "Success Add device",
                    "value": {
                      "message": "User Created",
                      "data": {
                        "id": "random string for id contact",
                        "firstName": "firstName",
                        "lastName": "lastName",
                        "email": "email@email.com",
                        "phone": "1234567890"
                      },
                      "meta": {
                        "location": "https://api/v1/user/1"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Contact Management"
        ],
        "summary": "Update User Contact",
        "description": "Endpoint for Update User Contact",
        "requestBody": {
          "description": "User Contact Data",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/contactReq"
              },
              "examples": {
                "Update Email": {
                  "description": "User Data for Update User Contact",
                  "value": {
                    "firstName": "old firstName",
                    "lastName": "old lastName",
                    "email": "new email@email.com",
                    "phone": "old 1234567890"
                  }
                },
                "Update All Contact Data": {
                  "description": "User Data for Update All Contact Data",
                  "value": {
                    "firstName": "new firstName",
                    "lastName": "new lastName",
                    "email": "new email@email.com",
                    "phone": "new 1234567890"
                  }
                },
                "Update First Name": {
                  "description": "User Data for Update User firstName",
                  "value": {
                    "firstName": "new firstName",
                    "lastName": "old lastName",
                    "email": "old email@email.com",
                    "phone": "old 1234567890"
                  }
                },
                "Update Last Name": {
                  "description": "User Data for Update User lastName",
                  "value": {
                    "firstName": "old firstName",
                    "lastName": "new lastName",
                    "email": "old email@email.com",
                    "phone": "old 1234567890"
                  }
                },
                "Update Phone": {
                  "description": "User Data for Update User Phone",
                  "value": {
                    "firstName": "old firstName",
                    "lastName": "old lastName",
                    "email": "old email@email.com",
                    "phone": "new 1234567890"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/contactRes"
                },
                "examples": {
                  "success": {
                    "description": "Success Add device",
                    "value": {
                      "message": "User Created",
                      "data": {
                        "id": "random string for id contact",
                        "firstName": "firstName",
                        "lastName": "lastName",
                        "email": "email@email.com",
                        "phone": "1234567890"
                      },
                      "meta": {
                        "location": "https://api/v1/user/1"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Contact Management"
        ],
        "summary": "Contact List",
        "description": "Endpoint for show Users List",
        "parameters": [
          {
            "$ref": "#/components/parameters/contact_id"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Forbidden"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contacts/{contact_id}": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Contact Management"
        ],
        "summary": "Get Contact Data",
        "description": "Endpoint for show Contact Data",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/contactRes"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Forbidden"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Contact Management"
        ],
        "summary": "Delete Contact Data",
        "description": "Endpoint for delete Contact Data",
        "responses": {
          "204": {
            "description": "The resource was deleted successfully"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "BadRequest": {
                    "$ref": "#/components/examples/BadRequest"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Unauthorized"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Unauthorized": {
                    "$ref": "#/components/examples/Forbidden"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error"
                },
                "examples": {
                  "Forbidden": {
                    "$ref": "#/components/examples/NotFound"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/defaultUserSchema"
                },
                "examples": {
                  "defaultResponse": {
                    "$ref": "#/components/examples/defaultResponse"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "user_id": {
        "name": "user_id",
        "in": "path",
        "description": "User ID",
        "required": true,
        "schema": {
          "type": "string",
          "maxLength": 100,
          "pattern": "[\\n\\s\\w\\W^$]"
        },
        "example": "1"
      },
      "contact_id": {
        "name": "contact_id",
        "in": "path",
        "description": "Contact ID",
        "required": true,
        "schema": {
          "type": "string",
          "maxLength": 100,
          "pattern": "[\\n\\s\\w\\W^$]"
        },
        "example": "1"
      }
    },
    "examples": {
      "defaultResponse": {
        "description": "Default User Response",
        "summary": "Default User Response",
        "value": {
          "success": true,
          "message": "Success.",
          "data": {},
          "meta": {}
        }
      },
      "BadRequest": {
        "description": "400 Bad Request",
        "summary": "Username id already exists, choose another one",
        "value": {
          "message": "Error: username id already exists, choose another one."
        }
      },
      "Unauthorized": {
        "description": "401 Wrong username or password.",
        "summary": "Wrong username or password",
        "value": {
          "message": "Wrong username or password"
        }
      },
      "Forbidden": {
        "description": "403 Forbidden",
        "summary": "Forbidden",
        "value": {
          "message": "Forbidden"
        }
      },
      "NotFound": {
        "description": "404 Not Found",
        "summary": "Not Found.",
        "value": {
          "message": "Error: not found."
        }
      }
    },
    "responses": {},
    "schemas": {
      "login": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "username": {
            "type": "string",
            "maxLength": 500,
            "pattern": "[\\n\\s\\w\\W^$]"
          },
          "password": {
            "type": "string",
            "maxLength": 500,
            "pattern": "[\\n\\s\\w\\W^$]"
          }
        }
      },
      "register": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "username": {
            "type": "string",
            "maxLength": 500,
            "pattern": "[\\n\\s\\w\\W^$]"
          },
          "password": {
            "type": "string",
            "pattern": "[\\n\\s\\w\\W^$]",
            "maxLength": 500
          },
          "name": {
            "type": "string",
            "pattern": "[\\n\\s\\w\\W^$]",
            "maxLength": 500
          }
        }
      },
      "contactReq": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "firstName": {
            "type": "string",
            "maxLength": 500,
            "pattern": "[\\n\\s\\w\\W^$]"
          },
          "lastName": {
            "type": "string",
            "pattern": "[\\n\\s\\w\\W^$]",
            "maxLength": 500
          },
          "email": {
            "type": "string",
            "pattern": "[\\n\\s\\w\\W^$]",
            "maxLength": 500
          },
          "phone": {
            "type": "string",
            "pattern": "[\\n\\s\\w\\W^$]",
            "maxLength": 500
          }
        }
      },
      "defaultUserSchema": {
        "type": "object",
        "required": [
          "data"
        ],
        "additionalProperties": false,
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string",
            "maxLength": 100,
            "pattern": "[\\n\\s\\w\\W^$]"
          },
          "data": {
            "type": "object",
            "additionalProperties": false
          },
          "meta": {
            "type": "object",
            "additionalProperties": false
          }
        }
      },
      "contactRes": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "message": {
            "type": "string",
            "maxLength": 100,
            "pattern": "[\\n\\s\\w\\W^$]"
          },
          "data": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": "string",
                "maxLength": 100,
                "pattern": "[\\n\\s\\w\\W^$]"
              },
              "firstName": {
                "type": "string",
                "maxLength": 100,
                "pattern": "[\\n\\s\\w\\W^$]"
              },
              "lastName": {
                "type": "string",
                "maxLength": 100,
                "pattern": "[\\n\\s\\w\\W^$]"
              },
              "email": {
                "type": "string",
                "maxLength": 100,
                "pattern": "[\\n\\s\\w\\W^$]"
              },
              "phone": {
                "type": "string",
                "maxLength": 100,
                "pattern": "[\\n\\s\\w\\W^$]"
              }
            }
          },
          "meta": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "location": {
                "type": "string",
                "maxLength": 100,
                "pattern": "[\\n\\s\\w\\W^$]"
              }
            }
          }
        }
      },
      "error": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "message": {
            "type": "string",
            "maxLength": 500,
            "pattern": "[\\n\\s\\w\\W^$]"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Authentication with user token"
      }
    }
  }
}